[package]
name = "rust-serde-benchmarks"
version = "0.0.1"
authors = ["erick.tryzelaar@gmail.com"]

[dependencies.capnp]
#git = "file:///Users/erickt/projects/rust/capnproto-rust"
git = "https://github.com/dwrensha/capnproto-rust"

[dependencies.msgpack]
#git = "https://github.com/mneumann/rust-msgpack"
#git = "https://github.com/erickt/rust-msgpack"
git = "file:///Users/erickt/projects/rust/rust-msgpack"

[dependencies.serde]
#git = "file:///Users/erickt/projects/rust/rust-serde"
git = "https://github.com/erickt/rust-serde"

[dependencies.serde_macros]
#git = "file:///Users/erickt/projects/rust/rust-serde"
git = "https://github.com/erickt/rust-serde"

[dependencies.tnetstring]
git = "https://github.com/erickt/rust-tnetstring"
