[package]
name = "rust-serde-benchmarks"
version = "0.0.1"
authors = ["erick.tryzelaar@gmail.com"]

[dependencies.capnp]
git = "https://github.com/dwrensha/capnproto-rust"

[dependencies.msgpack]
git = "https://github.com/erickt/rust-msgpack"

[dependencies.serde]
git = "https://github.com/erickt/rust-serde"

[dependencies.serde_macros]
git = "https://github.com/erickt/rust-serde"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf"
