[package]
name = "rust-serde-benchmarks"
version = "0.0.1"
authors = ["erick.tryzelaar@gmail.com"]
build = "build.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
bincode = "*"
capnp = "*"
num = "*"
rustc-serialize = "*"
rmp = "*"
#protobuf = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf"

[profile.bench]
#opt-level = 0
